# Generated by Django 5.1.1 on 2024-12-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodlist',
            name='Last_Donate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
