# Generated by Django 5.1.4 on 2024-12-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_project', '0002_bloodlist_last_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodlist',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
