# Generated by Django 5.1.4 on 2024-12-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_project', '0003_bloodlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodlist',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='donor_images/'),
        ),
    ]
